spring.application.name=api-gateway
server.port=8084
storage.service.url=http://edgesense-storage-nlb-595831d2cf6a0cad.elb.eu-west-1.amazonaws.com:8082
notification.service.url=http://notification.edgesense.local:8083
